"""initial schema

Revision ID: 20260715_0001
Revises:
Create Date: 2026-07-15 11:56:04.386041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260715_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('paper_limit', sa.Integer(), nullable=False),
    sa.Column('refresh', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'waiting_input', 'completed', 'failed', 'cancelled', name='runstatus', native_enum=False), nullable=False),
    sa.Column('current_phase', sa.Enum('plan', 'discover', 'extract', 'analyze', 'synthesize', 'verify', 'finalize', name='agentphase', native_enum=False), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.Column('input_context_json', sa.JSON(), nullable=False),
    sa.Column('pending_question', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_agent_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.String(length=2000), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_paper_id'), ['paper_id'], unique=True)

    op.create_table('relation_cache',
    sa.Column('pair_hash', sa.String(length=64), nullable=False),
    sa.Column('sig_lo', sa.Text(), nullable=False),
    sa.Column('sig_hi', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pair_hash')
    )
    with op.batch_alter_table('relation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relation_cache_model'), ['model'], unique=False)

    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.Enum('plan', 'discover', 'extract', 'analyze', 'synthesize', 'verify', 'finalize', name='agentphase', native_enum=False), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_event_sequence')
    )
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_events_run_id'), ['run_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('plan', 'discover', 'extract', 'analyze', 'synthesize', 'verify', 'finalize', name='agentphase', native_enum=False), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_step_sequence')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('intervention', sa.String(length=500), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_paper_id'), ['paper_id'], unique=False)

    op.create_table('agent_artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('source_step_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_step_id'], ['agent_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'kind', 'version', name='uq_agent_artifact_version')
    )
    with op.batch_alter_table('agent_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_artifacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('agent_tool_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('artifact_ids_json', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_arguments_hash'), ['arguments_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_tool_name'), ['tool_name'], unique=False)

    op.create_table('contradictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_a_id', sa.Integer(), nullable=False),
    sa.Column('claim_b_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_a_id', 'claim_b_id', name='uq_claim_pair')
    )
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradictions_claim_a_id'), ['claim_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradictions_claim_b_id'), ['claim_b_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradictions_claim_b_id'))
        batch_op.drop_index(batch_op.f('ix_contradictions_claim_a_id'))

    op.drop_table('contradictions')
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_tool_name'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_step_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_arguments_hash'))

    op.drop_table('agent_tool_calls')
    with op.batch_alter_table('agent_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_artifacts_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_artifacts_kind'))

    op.drop_table('agent_artifacts')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_paper_id'))

    op.drop_table('claims')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_events_event_type'))

    op.drop_table('agent_events')
    with op.batch_alter_table('relation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relation_cache_model'))

    op.drop_table('relation_cache')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_paper_id'))

    op.drop_table('papers')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
